language: perl

install:
  - "cpanm --quiet --installdeps --notest RDF::Trine"
  - "cpanm --quiet --notest Module::Install::AuthorTests"
meta.before_script:
  - "cd RDF-Trine"
script:
  - "perl Makefile.PL && make test"
