language: perl

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  - MODULE_DIR=RDF-Endpoint
  - MODULE_DIR=RDF-LinkedData-Apache
  - MODULE_DIR=RDF-Query
  - MODULE_DIR=RDF-Trine
  - MODULE_DIR=RDF-Trine-Iterator-Incremental
  - MODULE_DIR=RDF-Trine-Model-Rules
  - MODULE_DIR=RDF-Trine-Node-Literal-XML
  - MODULE_DIR=RDF-Trine-XS

before_install:
  - cd $MODULE_DIR
  - cpanm --installdeps --notest . 
